server:
  port: 60000

spring:
  cloud:
    config:
      name: user-service
    openfeign:
      loadbalancer:
        ribbon:
          enable: false
  application:
    name: user-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

greeting:
  message: Welcome to the Simple E-commerce.

logging:
  level:
    com.example.userservice: DEBUG
  pattern:
    correlation: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus

order-service-url: ${ORDER-SERVICE-URL}

gateway:
  ip: ${GATEWAY_IP}

token:
  expiration_time: ${TOKEN_EXPIRATION_TIME}
  secret: ${TOKEN_SECRET}

